### ISSUE TITLE
sdlRenderObject setAnchor()

### ISSUE THREAD

**Issue by INTr0py** [EthanShimooka/BAA#85]
Don't know why setAnchor is taking in doubles then implicitly casting to float. Would it make more sense to make anchors floats all around?

`void SDLRenderObject::setAnchor(double a, double b){ anchor.x = (float) a; anchor.y = (float) b; }`

**Comment by Ricardo-Murillo** [comment]
I was having some issues with the way the typecasting worked. The compiler
always assumes that something like 4.04 is a double, and since there were
two versions of setAnchor (float and int), it was confused over which one
to typecast the double into.

**Comment by INTr0py** [comment]
Got it!
